ThemeBootstrapBundle_elements:
    pattern:  /elements
    defaults: { _controller: ThemeBootstrapBundle:Default:elements }

ThemeBootstrapBundle_elements:
    pattern:  /elements
    defaults: { _controller: ThemeBootstrapBundle:Default:elements }

ThemeBootstrapBundle_docs:
    pattern:  /docs
    defaults: { _controller: ThemeBootstrapBundle:Default:docs }

ThemeBootstrapBundle_jqueryui:
    pattern:  /jqueryui
    defaults: { _controller: ThemeBootstrapBundle:Default:jqueryui }

ThemeBootstrapBundle_javascript:
    pattern:  /javascript
    defaults: { _controller: ThemeBootstrapBundle:Default:javascript }

ThemeBootstrapBundle_xhtmlTestPage:
    pattern:  /xhtmlTestPage
    defaults: { _controller: ThemeBootstrapBundle:Default:xhtmlTestPage }

ThemeBootstrapBundle_listGrid:
    pattern:  /listgrid
    defaults: { _controller: ThemeBootstrapBundle:Default:listGrid }

ThemeBootstrapBundle_listStacked:
    pattern:  /liststacked
    defaults: { _controller: ThemeBootstrapBundle:Default:listStacked }

ThemeBootstrapBundle_form:
    pattern:  /form
    defaults: { _controller: ThemeBootstrapBundle:Default:form }

ThemeBootstrapBundle_homepage:
    pattern:  /
    defaults: { _controller: ThemeBootstrapBundle:Default:index }
